spring:
  application:
    name: "helpdesk-project"

  datasource:
    url: jdbc:mysql://localhost:3306/springai-chatbot?useSSL=false&serverTimezone=UTC
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      base-url: http://localhost:12434/v1
      api-key: docker

      chat:
        options:
          model: smollm2:135M-Q4_K_M

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  profiles:
    active: dev

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

